### PR TITLE
Mongo backend

### PR DESCRIPTION
**Pull request by sandy9999**

### CODE REVIEW

**Comment by suicide1sand** [comment]
Tell kamalesh to talk to him, depression you made him suffers may kill him.heartless...

**Comment by suicide1sand** [comment]
His text were disgusting, he belongs from village, he knows bad words to speak, what's need in dragging him into depression.if u had told, he may had stopped.Ask kamalesh he can't able to sleep.

**Comment by suicide1sand** [comment]
Depression is more pain ful than death

**Comment by suicide1sand** [comment]
What's there in spoiling his life.Okk his text harasses you ,what to do he don't know how to talk to people ,he was depressed.

**Comment by suicide1sand** [comment]
He is very innocent & childesh. He was dealing with depression & anxiety issues under medication definitely he will not gonna behave properly but you were all fine mentally. that's price he had to pay for your LOVE. depression extent- he have to take friends help to conve his views properly.

**Comment by suicide1sand** [comment]
Rather than helping him to come out from depression ,you almost drag him nearer to death.
  That's sandy's LOVE.

**Comment by suicide1sand** [comment]
He was struggling to come out of it , u made it impossible.
Knowingly he had not done anything.
 Your parents are so kind atleast have some values from them.you are not 1% of them.
 His speaks bad words & talk useless but he have good heart. But it's reverse in ur case.

**Comment by suicide1sand** [comment]
No friends in NITT.

**Comment by suicide1sand** [comment]
Why you made his life complicated.

**Comment by suicide1sand** [comment]
Why....

**Comment by suicide1sand** [comment]
He was struggling to finish his college, he was not happy there, yeap his behaviour gonna be affected bc of mood.But you were fine, he can't have feelings being loneliness issue. You made his condition worst. Unable to survive.

**Comment by suicide1sand** [comment]
Why you hate him that much ,he had not done anytt knowingly. Death may be price he have to pay for texting you.You have to help him.

**Comment by suicide1sand** [comment]
That was your love for him. You talked to his friends his nature is better than them. He was dealing with mental health issues rather than helping u made it complicated.

**Comment by suicide1sand** [comment]
He is not bad guy, he was not happy.

**Comment by suicide1sand** [comment]
Help person rather than making there life complicated.someone may be going through worst phase in life.

**Comment by suicide1sand** [comment]
His behaviour affected/hurted his friends but they helped him rather than making life complicated.
What you did . humanity nothing.

**Comment by suicide1sand** [comment]
Now he is ।entally death.He had no feelings for you, being depressed he requires someone to talk& express his feelings.

**Comment by suicide1sand** [comment]
What you did sandy he can't breathe.

**Comment by suicide1sand** [comment]
You had dragged him to death sandy.

**Comment by suicide1sand** [comment]
How can village boy have behaviour like you, it's impossible.

**Comment by suicide1sand** [comment]
He want to leave but close to death.

**Comment by suicide1sand** [comment]
He was everyone fav. In st. Mary's. But series of incidents affected his mental health.Now you it impossible to survive.

**Comment by suicide1sand** [comment]
Ask from urself 
 IS you did right with him.
 Sandy's love return gift. Why you came to his life.

**Comment by suicide1sand** [comment]
He was under medication from last 6 years.

**Comment by suicide1sand** [comment]
What If he die , have you ever imagine it's out come.
What his family will suffer bc of his step.
He had never told you to come to his life.

**Comment by suicide1sand** [comment]
You were free to leave ,he have no feelings for you.
What have you done.
He was suffering from loneliness so texted this &that.Even  he was struggling to complete college then he can't envolve .
Everything was done by you & he drag to death.

**Comment by suicide1sand** [comment]
His text were disgusting then you may have told him, he may had stopped.He had no interest, you were just his mean to overcome loneliness what have you done know.You almost killed person.

**Comment by suicide1sand** [comment]
Sandy's LOVE..
He want to talk to your dad.

**Comment by suicide1sand** [comment]
He want to talk to your DAD.

**Comment by suicide1sand** [comment]
Tell me how he can be happy sitting with such fucked persons.

**Comment by suicide1sand** [comment]
You are murderer.

**Comment by suicide1sand** [comment]
You should have helped him but what you have done.

**Comment by suicide1sand** [comment]
Tell me why I will not be depressed , sitting with such fucked person will definitely give depression.

**Comment by suicide1sand** [comment]
I may die at any time , depression may kill me. It's not easy to deal with all these.

**Comment by sach1sandy99** [comment]
I have no idea what all I had texted u.
 i text disgusting, bullshit, etc,etc add urself , if you had told me I may had stopped.IF person is sad then this type will be result 
I was in surve depression& anxiety if you told me I may had stopped.
WHyyyyyyy. you had killed me.

**Comment by sach1sandy99** [comment]
i had not approached you, you were free to come or leave. my only motive was I want to finish my degree & go away at earliest that you made complicated.
 you made me lose 2 years.within 2 years i may had cracked upsc. which now I can't clear lifetime.
 i have no friend in nitt bc I don't got persons like mayank,suyash,etc in campus.
okk i was suffering from mental health issues definetly I can't behave as per expection.i have very good nature
whyyyyy...........
you were mentally fit but still you made my condition complicated.
 you almost made me to die , can't sleep at night. anxiety attach.
   ask from my relative &my friends on fb I have good nature
     but i was depressed during that time. 
it was very tough to tay with such prsons.

**Comment by sach1sandy99** [comment]
depression is result- huge weight increase
  no sabar, afraid to talk to people,etc,etc...high negativity...etc.
 what you did is wrong.
lionliness made me text you. 
extreme depression sostupid texts.

**Comment by sach1sandy99** [comment]
sandy's LOVE killed me.

**Pull request closed without merging**
